### ISSUE TITLE
error while installing python.

### ISSUE THREAD

**Issue by ulqi0rra** [SenZmaKi/Senpwai#10]
So while running the installer, i'm coming across the error," Cannot find the file specified." when it gets to installing python which is already installed on my device.
![Screenshot 2023-10-13 125350](https://github.com/SenZmaKi/Senpwai/assets/115228867/34005825-5148-4d4d-bd12-2b128f187622)

**Comment by SenZmaKi** [comment]
What Operating System are you on?

Seems like this error is occurring when the app attempts to start,  press `Win+R` then type `%appdata%\..\Local\Programs\Senpwai` and press Enter, is there a folder named .venv? Also it's better if we talk on the [discord](https://discord.gg/invite/e9UxKuyDX2)
