### ISSUE TITLE
Senpwai versions not opening

### ISSUE THREAD

**Issue by Demi19** [SenZmaKi/Senpwai#12]
I have been using Senpwai (v2.0.0) for some time now and so far, it worked great but recently I decided to upgrade it to the newest version possible so when I downloaded the latest version (2.0.4) and installed it. It installed properly but when I tried to open it. It didn't do anything at all. So, when I tried to reinstall the older version (v2.0.0) which I was using it open up properly but when I search for the anime it shows anime not found in animepahe. Have tried all of the new version the last version that opened was 2.0.1 and after that none.

**Comment by SenZmaKi** [comment]
Sorry for the late response I've been busy fixing all the stuff you've mentioned, I've fixed everything you've mentioned in the latest [version v2.0.5](https://github.com/SenZmaKi/Senpwai/releases/tag/v2.0.5). 

Also try and update the app as frequently as possible lol cause Senpwai is still a pretty "young" app so stuff change and improve quickly per update, for instance v2.0.0 had had really bad ram usage and Gogoanime barely ever worked, in the most recent updates both of those have been fixed, the app also supports auto-downloading new episodes of an anime upon release.

Be sure to let me know if you ran into any more issues.
