### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by ZetsApocNow** [SenZmaKi/Senpwai#16]
Search crashes on searching various shows like Air Gear and Demon Slayer, just endless Loading... and searching for anything else, shows the animes but selecting does nothing.

Gogoanime download doesn't seem to work either. Can search and select then it gathers download links and it just sits there. 

Edit - HLS seems to fix gogo.

Other than that, it's a great little program.

**Comment by SenZmaKi** [comment]
https://github.com/SenZmaKi/Senpwai/assets/90490506/e3399733-f6de-424b-bbb1-039f653e1eca

Everything seems to be working fine for me, can you send a video portraying this behaviour

**Comment by SenZmaKi** [comment]
Closing cause of inactivity
