### ISSUE TITLE
Update requirements.txt to include cx_Freeze

### ISSUE THREAD

**Issue by Code-Blender-7** [SenZmaKi/Senpwai#19]
### Adding cx_Freeze for virtual environment enchancement
Download the entire repository requirements at once in case that the repo is cloned in a virtual environment.
It saves people's time and be less annoying.

### Updated code ([requirements.txt](https://github.com/SenZmaKi/Senpwai/blob/master/requirements.txt))
```
anitopy==2.1.1
appdirs==1.4.4
pylnk3==0.4.2
bs4==0.0.1
yarl==1.9.2
requests==2.31.0
cryptography==41.0.3
PyQt6==6.6.0
tqdm==4.66.1
argparse==1.4.0
cx_Freeze==6.15.12
```

**Comment by SenZmaKi** [comment]
The problem with this is that `cx_Freeze` is only required during the build process, some people may opt to just run it directly via python e.g., Linux users, so I didn't want to potentially add bloatware to one's system. So I made it such that if they wanna build it then the command installs `cx_Freeze` first, if they don't well and good no bloatware.
