### ISSUE TITLE
Picky Me

### ISSUE THREAD

**Issue by 99keyz** [SenZmaKi/Senpwai#2]
Im sorry for the report but I prefer Dub Anime, Yet the website your wonderful program collects its media from has a finite amount of Dubbed Shows.

**Comment by SenZmaKi** [comment]
Don't apologise, feedback helps me make Senpwai better. I'm looking to implement scraping from more sites incase animepahe doesn't have the anime the user wants or in your case the dub, but I can't promise anything anytime soon cause I'm sick and I also have exams this upcoming week

**Comment by SenZmaKi** [comment]
In the new version [new version](https://github.com/SenZmaKi/Senpwai/releases), with the addition of Gogoanime that has almost all dubs,  I think your issue is resolved
