### ISSUE TITLE
senpcli: How to change the download folder

### ISSUE THREAD

**Issue by hillz2** [SenZmaKi/Senpwai#26]
Hi, I'm using `senpcli` on ubuntu and the default download folder always points to `/root/Downloads/Anime` so I have to move the downloaded episodes manually to my desired folder `/Media`. Is there a way to set the download folder before running the command ?

**Comment by KKonaOG** [comment]
Please see this senpcli-guide: https://github.com/SenZmaKi/Senpwai/blob/master/docs/senpcli-guide.md

If you look in ~/.config/Senpwai (HOME_DIRECTORY/.config/Senpwai) you should see a json file called settings.json where you can modify the "default" settings of the application.

See below for an example image:

![image](https://github.com/SenZmaKi/Senpwai/assets/38236274/f1b60c48-331e-4c55-9881-7a8b1042334c)

**Comment by hillz2** [comment]
What's gonna happen if I add more than one download paths when downloading with `senpcli` ?

**Comment by KKonaOG** [comment]
> What's gonna happen if I add more than one download paths when downloading with `senpcli`?

I am pretty sure it will default to the first folder in the list. I have not used that functionality. @SenZmaKi would have to answer that one for you.

**Comment by SenZmaKi** [comment]
> What's gonna happen if I add more than one download paths when downloading with `senpcli` ?

It'll search within the list of folders trying to find a folder with a similar name as the title of an anime you are about to download in order to detect episodes you do not have, if it can't one find it'll just download to the first folder
