### ISSUE TITLE
Error while downloading on the first step.

### ISSUE THREAD

**Issue by toons0ani** [SenZmaKi/Senpwai#28]
Hey,
 Your downloader is really great, I use it for downloading anime and watch them on my non-smart tv. 

So the problem i found was on the 1st step of downloading. 

The image - ![stuck a](https://github.com/SenZmaKi/Senpwai/assets/161406872/265cf191-a09b-45c1-82ac-7377fa58dd0d)

1st is stuck than everything disappears 

![image](https://github.com/SenZmaKi/Senpwai/assets/161406872/c92218f9-3371-4bbc-9fd3-abf341039fa1)
 so its stuck than disappear
it didn't download any anime either after 5 minutes of waiting.
Note: I had changed the background image because i can't see directly to light image.

Hope it will be fixed soon)

**Comment by toons0ani** [comment]
error reason found. 
Animepehe is preventing scraping.

**Comment by SenZmaKi** [comment]
When you check Gintama dub on [gogoanime](https://anitaku.to/category/gintama-dub)  you find that the episodes end at episode 49 so try limiting your download to episode 49 cause currently the app uses the sub episode count so it can't really know that the dub episodes are not yet available. 

Also join the [discord](https://discord.gg/invite/e9UxkuyDX2), I respond faster there

**Comment by toons0ani** [comment]
Thanks for the update. I appreciate it.
