### ISSUE TITLE
Crashing 

### ISSUE THREAD

**Issue by ConstantinXI** [SenZmaKi/Senpwai#3]
The app is just crashing, reinstalled it multiple times :/ 

https://github.com/SenZmaKi/Senpwai/assets/135034982/c0571860-95aa-4cb4-883c-369c47e9445a

**Comment by SenZmaKi** [comment]
Thank you for posting your issue and providing a video too, from what I'm seeing, you've given it a folder that requires administrator access, instead of C:\Users\Erwann\Downloads try C:\Users\PC\Downloads, let me know if it works or not
