### ISSUE TITLE
gogoanime doesn't work

### ISSUE THREAD

**Issue by k0kUro** [SenZmaKi/Senpwai#34]
I searched an anime on the gogoanime option and clicked it. The problem is I can't open the page for the anime, it only keeps loading.
![Senpwai 10_04_2024 3_08_18 AM](https://github.com/SenZmaKi/Senpwai/assets/166550844/8beda32b-8c99-4322-b563-0881900f0f4c)

**Comment by k0kUro** [comment]
I forgot to mention that this happened after I clicked the result that came up on the gogoanime search.

**Comment by f4rh4d-4hmed** [comment]
Its working for me. Check your internet connection and check if Gogoanime is blocked from your network by visiting the website. You can also check if its using cloudflare protection when you try to get in the website. If its blocked on your network you can use vpn and if cloudflare protection than just complete the captcha menually. This may help.

**Comment by ZetsApocNow** [comment]
I still have the issue

**Comment by SenZmaKi** [comment]
@k0kUro @ZetsApocNow 
Fixed #35
