### ISSUE TITLE
Got error while installing using pip

### ISSUE THREAD

**Issue by ninko76** [SenZmaKi/Senpwai#37]
![Screenshot 2024-04-22 134425](https://github.com/SenZmaKi/Senpwai/assets/103625285/85372af2-65c8-447a-beee-9b290ab2c3e1)

**Comment by SenZmaKi** [comment]
1. The command is `senpcli` not "sempcli"
2. As for that weird pylnk3.exe error I honestly don't know what's wrong cause it works fine for me, maybe use the [setup](https://github.com/SenZmaKi/Senpwai/releases/latest/download/Senpwai-setup.exe)

**Comment by f4rh4d-4hmed** [comment]
[ninko76](https://github.com/ninko76), 
It seem you do not have required permission to install library. You can try those solutions-
1. use this ```pip3 install -r requirements.txt --user```
2. if the step 1 doesn't help try using ```sudo``` in front for linux. For windows ran CMD as admin.
3. if both doesn't help use virtual environment. if no help either
4. try ```python -m pip install --upgrade pip
```
than try ```pip3 install -r requirements.txt --user``` again.
5. if none helps try uninstalling and reinstalling python. If you are using Windows, install python from MS Store
6. this will fix the issue for sure. If still not, consider building the app through github action.
7. This is going to fix for sure

**Comment by ninko76** [comment]
Installed in admin shell with --user and added to path manually and it works! 😁 Fixed

**Comment by f4rh4d-4hmed** [comment]
Glad to hear that it was Fixed.
