### ISSUE TITLE
gogo button

### ISSUE THREAD

**Issue by wipeout88** [SenZmaKi/Senpwai#39]
the link for gogo button / link is dead the domain has changed from anitaku.to to hianime.to can this please be updated ?, I tried doing it myself but I couldn't get the code to compile :(

**Comment by SenZmaKi** [comment]
anitaku.so was down for a while but it's back up again, gogoanime should work now

**Comment by f4rh4d-4hmed** [comment]
The link you are mentioning is completely different from Gogoanime. Even if you got the link changed in the code and compiled, it would never work. If https://anitaku.so/ is down for you, try using vpn. Though I didn't see any problem with https://anitaku.so/ as of 5/7/2024 to 5/9/2024.
