### ISSUE TITLE
Senpwai failed to install in Termux.

### ISSUE THREAD

**Issue by f4rh4d-4hmed** [SenZmaKi/Senpwai#41]
![Screenshot_20240515-185019_Termux](https://github.com/SenZmaKi/Senpwai/assets/161406872/8d3a10ca-2c32-4831-a0c2-5d242a47a7a0)

I tried to install senpcli by following given instruction. But it failed. Failed to build cffi.
Its in termux with Android 12.

**Comment by SenZmaKi** [comment]
the termux support is currently still unstable, even if it would have built there's an issue where when it downloads the files aren't available, I'm still trying to find a solution for that then I will address this

**Comment by f4rh4d-4hmed** [comment]
I see. As much as I know the newer android version doesn't allow applications to put file directly into the *emulated/0/Download* folder. The files are being downloaded into an App data folder which is directly inaccessible to non-root users. But to make those file accessible those downloaded files can be copied to *emulated/0/Download* folder after the downloading is done in app data. It requires termux storage setup to be done via ```termux-setup-storage``` command. Then command line Unix tools may help out. I think this way you may fix the issue. I will be waiting for the termux version of Senpwai.
