### ISSUE TITLE
Stuck on loading screen when choosing an anime

### ISSUE THREAD

**Issue by BabyPenewine** [SenZmaKi/Senpwai#42]
For some anime I download (usually the newer ones), when I search them on AnimePahe and press the anime name, it just gets stuck on the Zero Two loading screen for eternity. When I try to search for another anime, I can't even click on the anime names and I have to restart this app. Please fix!

**Comment by BabyPenewine** [comment]
Hi! I don't have a video example but here is an image:
![image](https://github.com/SenZmaKi/Senpwai/assets/99485963/d0959a58-014d-4d67-81b1-139afeab20b2)
It just stays on that screen for eternity it doesn't load at all

**Comment by SenZmaKi** [comment]
I meant an anime title as an example but this works. I have fixed it, when I release an update I'll tell you, also do you have any other titles with a similar problem or any other issues so that I can just address them all before I release the update?

**Comment by BabyPenewine** [comment]
sorry just saw this, i remember the Karakai Takagi-san movie and Girls Band Cry having the same problem. also possibly with Whisper Me a Love Song

**Comment by SenZmaKi** [comment]
It's ok, they all work now, closing this as completed
