### ISSUE TITLE
Shutdown after downloads are finished

### ISSUE THREAD

**Issue by CrazyGreekGR** [SenZmaKi/Senpwai#45]
It would be nice if there was an option to shutdown the computer after all downloads are finished. If there is this option somewhere, please point me to it :)

**Comment by SenZmaKi** [comment]
This is beyond the scope of Senpwai, you have to do it on your own. 

You can for instance schedule a shutdown based off the total download eta Senpwai shows, but this of course an estimation so it might shutdown before downloads complete or way after.

Or if you're familiar with the command line you can use [senpcli](https://github.com/SenZmaKi/Senpwai/blob/master/docs/senpcli-guide.md).

- Windows
 ```
senpcli "Boku No Hero Academia" && shutdown /s /f /t 0
```

- Linux/Mac 
```
senpcli "Boku No Hero Academia" && sudo shutdown -h now
```
This will prompt for your password after the download completes so you'll have to find a way around this incase you want it to automatically shutdown.

**Comment by sudoAlphaX** [comment]
> This will prompt for your password after the download completes

`systemctl poweroff` doesnt prompt me for password. Please check and confirm if its the same.

Regards

-- 
Pranaov S

Sent from my Android device


-------- Original Message --------

**Comment by sudoAlphaX** [comment]
> This will prompt for your password after the download completes

`systemctl poweroff` doesnt prompt me for password. Please check and confirm if its the same.

Regards

--  
sudoAlpha

Sent from my Android device using K-9 Mail


-------- Original Message --------

**Comment by CrazyGreekGR** [comment]
Aight, thank you!
