### ISSUE TITLE
Senpwai stops downloading after a certain amount of anime

### ISSUE THREAD

**Issue by CrazyGreekGR** [SenZmaKi/Senpwai#46]
Yesterday night, I started download of 21 anime because I hoard them on an hdd I have. Senpwai fully installed only 11 of them, while it reported the other 10 as complete but the files where 1kb and all of them unplayable of course. Why is that?

**Comment by SenZmaKi** [comment]
Honestly I don't really know, best guess would be the sites rate limited your ip, debugging this is pretty much impossible given I can't really download 21 anime in the hope it eventually bugs out. Open the settings folder then click the button to the top left corner with the settings.json path as it's text, then send the errors.log file in the opened folder here.

**Comment by blahblahfit** [comment]
I'm having a similar issue, regardless of a vpn, what anime or source it is downloaded from the app will request links then download episode 1 and 2 with a file size of 2kb and then crash.
