### ISSUE TITLE
A Copy Link Button

### ISSUE THREAD

**Issue by LazyDevUserX** [SenZmaKi/Senpwai#47]
Senpwai is great for scraping download links but in terms of speed a dedicaed download manager is better so a button to copy the donwload link would be nice to have

or maybe a way to export all the download links to a text file

I don't know if direct integration to a Downloader  like IDM is possible or not but that would be the greatest thing to have

**Comment by LazyDevUserX** [comment]
Maybe Somthing like this can work for IDM integration


 `import os

def download_with_idm(url):
    idm_path = r'"C:\Program Files (x86)\Internet Download Manager\IDMan.exe"'
    os.system(f'{idm_path} /d {url} /n /a')

def fetch_episode_links(anime_url):
    # scraping here
    links = []

    # Example scraping logic 
    response = requests.get(anime_url)
    soup = BeautifulSoup(response.text, 'html.parser')
    for a_tag in soup.find_all('a', href=True):
        links.append(a_tag['href'])

    # Download using IDM
    for link in links:
        download_with_idm(link)

    return links `

**Comment by SenZmaKi** [comment]
The slow download speeds aren't really cause of Senpwai but cause of the servers hosting the files so I highly doubt using an IDM will fix the issue cause the bottleneck is ultimately out of both of our controls

**Comment by LazyDevUserX** [comment]
Actually It can improve the download speed cause Download managers like IDM split the larger files into smaller section and simultaniously downloads them so download speed is higher compaared to defult download manager

**Comment by LazyDevUserX** [comment]
IDM integration will be a painfull process so a copy url button the the download section should be good enough

**Comment by SenZmaKi** [comment]
Supporting this in Senpwai is a pain since I'll have to figure out how to expose it in the UI and also handle os specific copy pasting, but with Senpcli this isn't an issue so I've added an option to instead just print the direct download links in Senpcli instead of downloading, it should also make automating the process of downloading with idm easier since you can just pipe Senpcli's output into idm

**Comment by SenZmaKi** [comment]
the update is out

**Comment by LazyDevUserX** [comment]
Thanks Appreciate The Effort
