### ISSUE TITLE
Feature Request: Minimize to tray button on tray icon

### ISSUE THREAD

**Issue by sudoAlphaX** [SenZmaKi/Senpwai#48]
It is currently difficult (probably not possible) to minimize senpwai to system tray when using a tiling window manager. Senpwai also doesnt close to tray on close.

I think it would be helpful if there is a minimize to tray button on the tray icon's context (right-click) menu.

**Comment by sudoAlphaX** [comment]
Turns out you can minimize senpwai to tray by clicking on the tray icon

**Comment by SenZmaKi** [comment]
As of [v2.1.15](https://github.com/SenZmaKi/Senpwai/releases/tag/v2.1.15) there is a minimize to tray on close setting now on top of the pre-existing clicking the tray icon
