### ISSUE TITLE
Error: Sowwy the onwy currently browser supported is google chrome. Please install it and try again..

### ISSUE THREAD

**Issue by protonssss** [SenZmaKi/Senpwai#5]
Hey! I really love this app. It used to work till yesterday for me. Now whenever I try to download any anime it shows an error related to Chrome even though I have Chrome installed on my PC. Any Solutions? Thank you.

**Comment by SenZmaKi** [comment]
Sorry about that, I've stopped working on new updates for version 1 cause currently I'm working on version 2, that has a graphical user interface and supports both Gogoanime and Animepahe, it should be out by next month. Also with version 2 for Animepahe you'll no longer need to have Chrome, no more failed downloads and crashes.

**Comment by SenZmaKi** [comment]
I released the [new version](https://github.com/SenZmaKi/Senpwai/releases), I think u might like it :)

**Comment by protonssss** [comment]
Hey, i'm unable to install it 
![Screenshot 2023-07-27 201105](https://github.com/SenZmaKi/Senpwai/assets/140023475/2505f346-368f-499f-9571-ef8bdad0f1e5)

**Comment by SenZmaKi** [comment]
I'm an idiot I forgorr sth, give me like 20 mins

**Comment by SenZmaKi** [comment]
I uploaded the (new new version)[https://github.com/SenZmaKi/Senpwai/releases]

**Comment by protonssss** [comment]
Thank you, I have installed the software now. Though I'm wondering usually how long does it take to retrieve download links? (It's been nearly 5 - 7 minutes)
![Screenshot (23)](https://github.com/SenZmaKi/Senpwai/assets/140023475/0d67252c-2210-4a75-a4c3-1baacbc02ac7)

**Comment by protonssss** [comment]
It's this [Anime
](https://anilist.co/anime/10029/Coquelicotzaka-kara)

**Comment by SenZmaKi** [comment]
For Animepahe it doesn't work well for old anime cause they usually dont have all the 3 qualities, and they label them so wrong like 720p they put as 620p, Idk why, fortunately we have Gogoanime as a fallback, try Gogoanime with this title "From Up on Poppy Hill"

**Comment by SenZmaKi** [comment]
I fixed the bug for the anime you mentioned, for old anime in general, it was a simple fix, I just wasn't thinking outside the box. So now downloads from Animepahe should in theory work 100% of the time and if they don't it's a bug so be sure to report it. And now we have the [final final final version](https://github.com/SenZmaKi/Senpwai/releases), trust.

**Comment by protonssss** [comment]
Thank You for the Final final final version!!
