### ISSUE TITLE
Feature request 

### ISSUE THREAD

**Issue by padranina** [SenZmaKi/Senpwai#51]
O encountered an issue that is if i download any anime it fetches link then calculates size, if i turn off pc it does it again. If possible it should store in storage. (If links don't change over time) 

And it doesn't have a auto resume feature that is if i close pc when an episode downloaded 50% it starts from beginning.

**Comment by SenZmaKi** [comment]
Recalculating sizes after shutdown doesn't seem that much of an annoyance that it'd justify storing sizes, from the app's perspective, past downloads don't exist after you close the app. Most users won't have this problem all that often and you can always enable skip calculating diwnload size for gogo. 

Resuming downloads after shutting down is a nightmare to implement given how varied a download can be; site, resolution, sub or dub, norm or hls etc. It is on the bucket list but I honestly can't promise anything.

**Comment by padranina** [comment]
> Recalculating sizes after shutdown doesn't seem that much of an annoyance that it'd justify storing sizes, from the app's perspective, past downloads don't exist after you close the app. Most users won't have this problem all that often and you can always enable skip calculating diwnload size for gogo.
> 
> Resuming downloads after shutting down is a nightmare to implement given how varied a download can be; site, resolution, sub or dub, norm or hls etc. It is on the bucket list but I honestly can't promise anything.

Well then don't do it as it will waste much of your time cause download link changes over time and who closes window when downloadin? 😂 
And if anyone closes 200-500MB and some seconds doesn't matter.

**Comment by padranina** [comment]
You can close this issue.
