### ISSUE TITLE
Greek letters not showing

### ISSUE THREAD

**Issue by CrazyGreekGR** [SenZmaKi/Senpwai#56]
Idk if this is a known issue, but greek letters in The Disasterous Life of Saiki K(specifically the letter Ψ/psi) is not added to the title of the anime when downloading. Just letting u know :)

![spinning pochita lol](https://i.makeagif.com/media/2-25-2023/4Ar4FN.gif)

**Comment by SenZmaKi** [comment]
You can't have a file/folder with special characters like greek letters so Senpwai strips them out from anime titles
________________________________
From: CrazyGreek ***@***.***>
Sent: Wednesday, August 7, 2024 2:45 AM
To: SenZmaKi/Senpwai ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [SenZmaKi/Senpwai] Greek letters not showing (Issue #56)


Idk if this is a known issue, but greek letters in The Disasterous Life of Saiki K(specifically the letter Ψ/psi) is not added to the title of the anime when downloading. Just letting u know :)

[spinning pochita lol]<https://camo.githubusercontent.com/0940eeadf06bb23a419c5a56d0d461e86557f756c0f8119782d707cde3c7232e/68747470733a2f2f692e6d616b65616769662e636f6d2f6d656469612f322d32352d323032332f34417234464e2e676966>

**Comment by SenZmaKi** [comment]
You can't have a file/folder with special characters like greek letters so Senpwai strips them out from anime titles
