### ISSUE TITLE
Tracked anime downloading in 360p when I set it to 720p

### ISSUE THREAD

**Issue by BabyPenewine** [SenZmaKi/Senpwai#58]
![image](https://github.com/user-attachments/assets/835a7e1d-0c1c-43f5-b5d9-087e2236d7ae)
![image](https://github.com/user-attachments/assets/2a311805-2b8f-43fa-95cd-1dad7322724e)
The 2.5 anime is a tracked anime, and as you see I set it to download at 720p, and in options I also put my preferred quality to be 720p, but for some reason today the new episode came out and its dimensions are in 360p.
Previously I did set it to download at 360p by default but I just changed it to 720p last week, but it seems like changing the quality doesn't affect tracked downloads. Can this be fixed or be an option? Thanks

**Comment by SenZmaKi** [comment]
Usually the app tries to find the next closest quality under the one you want if the one you want is unavailable, for instance if it can't find 720p it'll try 480p then 360p if 480p is also unavailable, most probably the quality that was out at the time was 360p or your settings changes were not saved, is this still happening?

**Comment by BabyPenewine** [comment]
Hey, I'm pretty sure the settings were saved as when I checked it was still at 720p. Also I tried deleting the 360p and downloading the 720p version that I preferred and it downloaded just fine, it's just for the auto download then it's stuck at 360p and I can't fix it. Thanks

**Comment by BabyPenewine** [comment]
Oh wait sorry I just checked and the newest episodes were 720p, must've been something my end or you fixed it. Thanks
