### ISSUE TITLE
Captcha Detected

### ISSUE THREAD

**Issue by 99keyz** [SenZmaKi/Senpwai#6]
Ive tried downloading Dragon Ball (1986) and Dragon Ball Z (1989) from GoGo.
I keep getting stopped with the Captcha block detected.Ive switched browsers to no luck so I decided to "Download in Browser" then it took me to "https://gotaku1.com/" wondering if it could be added as a Repo.

**Comment by SenZmaKi** [comment]
The captcha block thing sucks cause there's basically nothing I can do about it, it's like fighting against Google, cause they use Google Recaptcha. The download in browser opens your browser with the download links you just have to wait a bit for it to load. What do you mean by be added as a repo?

**Comment by 99keyz** [comment]
wondering if that other site could be added as a repository for downloads if its any better

**Comment by SenZmaKi** [comment]
Basically downloads for Gogoanime go are gotten from gotaku, they own gotaku if that makes. Try downloading an anime in your browser from Gogoanime, it'll redirect you to gotaku and that's where the captcha block is.
