### ISSUE TITLE
VCRUNTIME140.ddl not found

### ISSUE THREAD

**Issue by LazyDevUserX** [SenZmaKi/Senpwai#60]
![image](https://github.com/user-attachments/assets/0b1c0ed1-ee31-4e5c-802f-a491d94d1025)

**Comment by foxtbirdy** [comment]
Try to download the Microsoft Redistributable version. Your machine is missing a .ddl runtime file. You can find the file in this website. 
https://www.dll-files.com/vcruntime140.dll.html

**Comment by SenZmaKi** [comment]
As @foxtbirdy  as mentioned, you are probably running a fresh install of windows so you need [Microsoft Visual C++ Redistributable](https://aka.ms/vs/16/release/VC_redist.x64.exe)
