### ISSUE TITLE
Environment Variables are overwritten - BUG

### ISSUE THREAD

**Issue by azeem-yousaf** [SenZmaKi/Senpwai#61]
I've installed the latest version and It seems to have overwritten all of my environment variables.

Going forward the installer needs to append the new path rather than removing existing paths.

![image](https://github.com/user-attachments/assets/b961e330-f66c-4d0a-8980-8dbb0de90489)

Now I have to set everything back up :/

**Comment by SenZmaKi** [comment]
Sorry, I've been there too. This a Windows issue, Windows has a limit on the length of `PATH` and when you exceed it it erases it. There's no way for Senpwai or any other apps for that matter to address this given it's an upstream Windows issue. 

To avoid going over the length limit on `PATH` yiu can create other environment variables and reference them in `PATH`, e.g., `PATH1`, `PATH2`. Also check out [this tool](https://www.rapidee.com/en/about)
