### ISSUE TITLE
senpwai not openning

### ISSUE THREAD

**Issue by darkprime2525** [SenZmaKi/Senpwai#62]
when i try to open senpwai the error occors,

![Annotation 2024-11-14 090449](https://github.com/user-attachments/assets/1872d100-e042-4df6-b255-43263e5b0a61)

**Comment by SenZmaKi** [comment]
You need to install [Microsoft Visual C++ Redistributable](https://aka.ms/vs/16/release/VC_redist.x64.exe)

**Comment by darkprime2525** [comment]
> You need to install [Microsoft Visual C++ Redistributable](https://aka.ms/vs/16/release/VC_redist.x64.exe)

thanks bro it worked
