### ISSUE TITLE
senpwai doesent open

### ISSUE THREAD

**Issue by Billya4** [SenZmaKi/Senpwai#66]
when i try to launch senpwai, nothing happens. 
curiously when i maximize the explorer and then launch senpwai, the explorer window gets de-maximized (and senpwai doesent open)

i am using the latest version of senpwai
 i tried the latest version of python as well as 3.11
i also installed it from source, with the same results

[errors.log](https://github.com/user-attachments/files/17941363/errors.log)

**Comment by SenZmaKi** [comment]
Wait why are the paths in the error log appearing like my local pc setup
![image](https://github.com/user-attachments/assets/9edcbb1f-3242-494f-8060-386f4cf157d8)
Bruh what???

**Comment by SenZmaKi** [comment]
Anyway from the error logs it seems like your settings are corrupted, your tracking interval to specific. Find your settings file at `C:\Users\Your Name\AppData\Local\Programs\Senpwai\settings.json`, either delete it or set `tracking_interval` to a sane value like 1.
