### ISSUE TITLE
Spanish sites 

### ISSUE THREAD

**Issue by Dantesinferno11** [SenZmaKi/Senpwai#7]
I love the app and I would like to download anime from spanish sites like jkanime, animeflv, heneojara. Thanks you

**Comment by SenZmaKi** [comment]
I'm glad you like it, but unfortunately seeing as to how I don't speak Spanish so it'd be almost impossible for me to write scrapers for those sites, and after some back and forth with google translate I've found that practically all them only allow downloading in browser.

**Comment by Dantesinferno11** [comment]
Okay thanks you
