### ISSUE TITLE
is there a portable version for windows without installation?

### ISSUE THREAD

**Issue by candrapersada** [SenZmaKi/Senpwai#74]

**Comment by SenZmaKi** [comment]
Nope, I didn't really see a use case for it but you can I guess you can install it then zip the installation folder to make a portable version. It's usually installed at `C:/Users/YourName/AppData/Local/Roaming/Senpwai`.

**Comment by SenZmaKi** [comment]
Nope, I didn't really see a use case for it but you can I guess you can install it then zip the installation folder to make a portable version. It's usually installed at `C:\Users\YourName\AppData\Local\Programs\Senpwai`.

**Comment by candrapersada** [comment]
please make Senpwai.zip without having to install it first

**Comment by SenZmaKi** [comment]
I'm curious, why would anyone need this?

**Comment by candrapersada** [comment]
so that it can be used portably without installing it first

**Comment by SenZmaKi** [comment]
> so that it can be used portably without installing it first

why would anyone want to do that?

**Comment by candrapersada** [comment]
so that the data is not left behind on the PC/laptop and you can download anime on another PC/laptop without installing it again

**Comment by SenZmaKi** [comment]
> so that the data is not left behind on the PC/laptop and you can download anime on another PC/laptop without installing it again

The installer does not download anything during installation it simply decompresses the compressed app data into the target installation folder. If you want to use it on a different PC just copy paste the installer and run it. 

If you want to uninstall just click uninstall on the apps start menu in Windows, it wont leave anything behind aside from settings and error logs in the config folder which are <20MB, go to the about section of the app for a guide on how to delete the config folder.

**Comment by SenZmaKi** [comment]
A [portable release](https://github.com/SenZmaKi/Senpwai/releases/tag/v2.1.15) in now available in the
