### ISSUE TITLE
error main script 

### ISSUE THREAD

**Issue by allendbest** [SenZmaKi/Senpwai#75]
not working on windows server 2022
![Screenshot_2024-12-26-16-48-54-65_2665fb67b16260a8d818298cef8dc107](https://github.com/user-attachments/assets/3b9c524d-4c07-4eaf-9b8c-1e635645855c)

**Comment by SenZmaKi** [comment]
Try installing [Microsoft Visual C++ Redistributable](https://aka.ms/vs/16/release/VC_redist.x64.exe)
