### ISSUE TITLE
Aniwatch.to 

### ISSUE THREAD

**Issue by Dantesinferno11** [SenZmaKi/Senpwai#8]
this site uses different languages ​​not only english, maybe it can be implemented for those who don't speak much english

**Comment by SenZmaKi** [comment]
The site seems pretty good from a web-scraping perspective, except for one big flaw, they don't have download links, it's a streaming only site. This kinda defeats the purpose of Senpwai cause it's a batch anime downloader.

**Comment by Dantesinferno11** [comment]
Ok got it. So there is no way to add a website to download anime with different lenguage?

**Comment by SenZmaKi** [comment]
Honesty I don't know, the site would have to be scrapable in that they don't make browser checks like for instance [marin](https://marin.moe) or don't have captcha block like [gogoanime](https://gogoanime.cl) and they'd have direct download links not ones hosted on like mega, it might exist somewhere out there but I don't know, if you ever run into one be sure to let me know
